version: "3.8"

services:
  db:
    container_name: "workout-db"
    image: postgres:12.4-alpine
    volumes:
      - ./database/postgres-data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    restart: unless-stopped
    networks:
      - workout-network

networks:
  workout-network:
    driver: bridge
